services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - dagger-socket:/run/dagger
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn rag_app:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    environment:
      - DAGGER_HOST=unix:///run/dagger/engine.sock
      - _EXPERIMENTAL_DAGGER_RUNNER_HOST=unix:///run/dagger/engine.sock
      - QDRANT_URL=http://qdrant:6333
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - dagger-engine
      - qdrant
    networks:
      - dagger-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3

  dagger-engine:
    image: registry.dagger.io/engine:v0.18.6
    container_name: dagger-engine
    privileged: true
    volumes:
      - dagger-socket:/run/dagger
    networks:
      - dagger-net

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - dagger-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  dagger-socket:
  qdrant-data:

networks:
  dagger-net:
    driver: bridge