# SmartÆgent X-7 - Pure Temporal Architecture
name: smartagent-x7

services:
  # Main Chat Interface
  gradio:
    build:
      context: ./services/gradio_service
    ports:
      - "7860:7860"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TEMPORAL_HOST=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DOCUMENT_COLLECTION_NAME=${DOCUMENT_COLLECTION_NAME:-document_chunks}
    env_file:
      - .env
    depends_on:
      temporal:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    networks:
      - smartagent-net
    restart: unless-stopped

  # Workflow Composer Service (GraphQL API)
  workflow-composer:
    build:
      context: ./services/workflow_composer_service
    ports:
      - "8001:8001"  # GraphQL API endpoint
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TEMPORAL_HOST=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      temporal:
        condition: service_healthy
    networks:
      - smartagent-net
    restart: unless-stopped

  # Embedding Service (Temporal Activities)
  embedding-service:
    build:
      context: ./services/embedding_service
      args:
        EMBEDDING_MODEL_ARG: "BAAI/bge-small-en-v1.5"
    ports:
      - "8082:8082"  # Metadata endpoint
    environment:
      - TEMPORAL_HOST=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_TASK_QUEUE=embedding-task-queue
      - PYTHONPATH=/app
      - EMBEDDING_MODEL=BAAI/bge-small-en-v1.5
      - METADATA_PORT=8082
    volumes:
      - fastembed_models:/root/.cache/fastembed
    depends_on:
      temporal:
        condition: service_healthy
    networks:
      - smartagent-net
    restart: unless-stopped

  # Retriever Service (Temporal Activities)
  retriever-service:
    build:
      context: ./services/retriever_service
      args:
        EMBEDDING_MODEL_ARG: "BAAI/bge-small-en-v1.5"
    ports:
      - "8083:8083"  # Metadata endpoint
    environment:
      - QDRANT_HOST_FOR_SERVICE=http://qdrant:6333
      - QDRANT_API_KEY=${QDRANT_API_KEY:-}
      - TEMPORAL_HOST=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - METADATA_PORT=8083
      - TEMPORAL_TASK_QUEUE=retriever-task-queue
      - PYTHONPATH=/app
      - EMBEDDING_MODEL=BAAI/bge-small-en-v1.5
    volumes:
      - fastembed_models:/root/.cache/fastembed
    depends_on:
      qdrant:
        condition: service_healthy
      temporal:
        condition: service_healthy
    networks:
      - smartagent-net
    restart: unless-stopped

  # Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - smartagent-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "timeout", "5", "bash", "-c", "</dev/tcp/localhost/6333"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Temporal Server
  temporal:
    image: temporalio/auto-setup:1.24
    ports:
      - "7233:7233"
      - "8080:8080"  # Temporal Web UI
      - "7243:7243"  # Temporal HTTP API
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - smartagent-net
    healthcheck:
      test: ["CMD", "pgrep", "-f", "temporal-server"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  # PostgreSQL for Temporal
  postgresql:
    image: postgres:13
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_DB=temporal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smartagent-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Temporal Web UI
  temporal-ui:
    image: temporalio/ui:2.28.0
    ports:
      - "8081:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8081
    depends_on:
      temporal:
        condition: service_healthy
    networks:
      - smartagent-net

  # Temporal Worker Service (Workflows + Orchestration)
  temporal-worker:
    build:
      context: ./services/temporal_service
    environment:
      - TEMPORAL_HOST=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_TASK_QUEUE=document-processing-queue
      - DOCUMENT_COLLECTION_NAME=${DOCUMENT_COLLECTION_NAME:-document_chunks}
    depends_on:
      temporal:
        condition: service_healthy
    networks:
      - smartagent-net
    restart: unless-stopped
    stop_grace_period: 30s

volumes:
  qdrant_data:
  postgres_data:
  fastembed_models:

networks:
  smartagent-net:
    driver: bridge
