services:
  utility_service:
    activities:
      validate_inputs_activity:
        description: "Validates input parameters against schema requirements"
        task_queue: "utility-queue"
        timeout_seconds: 60
        retry_attempts: 3
        parameters:
          - name: "inputs"
            type: "object"
            description: "The input parameters to validate"
            required: true
          - name: "schema"
            type: "object"
            description: "JSON schema for validation"
            required: true
        returns:
          type: "object"
          description: "Validated and cleaned input parameters"
          
      format_response_activity:
        description: "Formats results for client UI presentation"
        task_queue: "utility-queue"
        timeout_seconds: 60
        retry_attempts: 3
        parameters:
          - name: "results"
            type: "object"
            description: "Raw results to format"
            required: true
          - name: "format_type"
            type: "string"
            description: "Desired format (json, html, markdown)"
            required: false
        returns:
          type: "object"
          description: "Formatted results ready for display"
  
  intent_service:
    activities:
      extract_context_activity:
        description: "Extracts search parameters or user intent from natural language"
        task_queue: "intent-queue"
        timeout_seconds: 120
        retry_attempts: 2
        parameters:
          - name: "query"
            type: "string"
            description: "User query text"
            required: true
          - name: "context_type"
            type: "string"
            description: "Type of context to extract (search, booking, recommendation)"
            required: false
        returns:
          type: "object"
          description: "Structured context parameters extracted from query"
  
  embedding_service:
    activities:
      generate_embeddings_activity:
        description: "Generates vector embeddings for text"
        task_queue: "embedding-queue"
        timeout_seconds: 180 
        retry_attempts: 3
        parameters:
          - name: "text"
            type: "string"
            description: "Text to embed"
            required: true
          - name: "model"
            type: "string" 
            description: "Embedding model to use"
            required: false
        returns:
          type: "array"
          items: "number"
          description: "Vector embedding of the input text"
  
  retriever_service:
    activities:
      semantic_search_activity:
        description: "Performs semantic search against vector database"
        task_queue: "retrieval-queue"
        timeout_seconds: 120
        retry_attempts: 3
        parameters:
          - name: "query_embedding"
            type: "array"
            description: "Query vector embedding"
            required: true
          - name: "collection_name"
            type: "string"
            description: "Vector collection to search"
            required: true
          - name: "limit"
            type: "integer"
            description: "Max number of results"
            required: false
        returns:
          type: "array"
          description: "List of search results with similarity scores"
      
      filter_results_activity:
        description: "Applies filters to search results"
        task_queue: "retrieval-queue"
        timeout_seconds: 60
        retry_attempts: 2
        parameters:
          - name: "results"
            type: "array"
            description: "Search results to filter"
            required: true
          - name: "filters"
            type: "object"
            description: "Filter criteria"
            required: true
        returns:
          type: "array"
          description: "Filtered search results"
      
      rank_results_activity:
        description: "Ranks results by relevance and user preferences"
        task_queue: "retrieval-queue" 
        timeout_seconds: 90
        retry_attempts: 2
        parameters:
          - name: "results"
            type: "array"
            description: "Results to rank"
            required: true
          - name: "user_preferences"
            type: "object"
            description: "User preference signals"
            required: false
        returns:
          type: "array"
          description: "Ranked results"

  ai_service:
    activities:
      generate_recommendations_activity:
        description: "Generate personalized recommendations using LLM"
        task_queue: "ai-queue"
        timeout_seconds: 240
        retry_attempts: 3
        parameters:
          - name: "user_preferences"
            type: "object"
            description: "User preferences and profile"
            required: true
          - name: "count"
            type: "integer"
            description: "Number of recommendations to generate"
            required: false
        returns:
          type: "object"
          description: "Generated recommendations with embeddings"
      
      process_booking_request_activity:
        description: "Process and validate booking requests using AI"
        task_queue: "ai-queue"
        timeout_seconds: 180
        retry_attempts: 2
        parameters:
          - name: "booking_intent"
            type: "object"
            description: "Extracted booking intent"
            required: true
          - name: "availability_data"
            type: "object"
            description: "Available options"
            required: true
        returns:
          type: "object"
          description: "Processed booking recommendation"

  booking_service:
    activities:
      check_availability_activity:
        description: "Check accommodation availability"
        task_queue: "booking-queue"
        timeout_seconds: 90
        retry_attempts: 3
        parameters:
          - name: "accommodation_id"
            type: "string"
            description: "ID of the accommodation"
            required: true
          - name: "check_in"
            type: "string"
            description: "Check-in date"
            required: true
          - name: "check_out"
            type: "string"
            description: "Check-out date"
            required: true
          - name: "guests"
            type: "integer"
            description: "Number of guests"
            required: true
        returns:
          type: "object"
          description: "Availability status and pricing"
      
      create_reservation_activity:
        description: "Create a new reservation"
        task_queue: "booking-queue"
        timeout_seconds: 150
        retry_attempts: 3
        parameters:
          - name: "booking_details"
            type: "object"
            description: "Complete booking information"
            required: true
          - name: "payment_info"
            type: "object"
            description: "Payment details"
            required: true
        returns:
          type: "object"
          description: "Reservation confirmation"
      
      get_booking_details_activity:
        description: "Retrieve booking confirmation details"
        task_queue: "booking-queue"
        timeout_seconds: 60
        retry_attempts: 2
        parameters:
          - name: "reservation_id"
            type: "string"
            description: "Reservation ID"
            required: true
        returns:
          type: "object"
          description: "Complete booking details"
