examples:
  - name: "Simple Search Pattern"
    description: "Basic pattern for search workflows"
    activities:
      - "validate_inputs_activity"
      - "extract_context_activity" 
      - "generate_embeddings_activity"
      - "semantic_search_activity"
      - "format_response_activity"
    
  - name: "Filter and Rank Pattern"
    description: "Pattern for workflows that need filtering and ranking"
    activities:
      - "validate_inputs_activity"
      - "semantic_search_activity"
      - "filter_results_activity"
      - "rank_results_activity"
      - "format_response_activity"
    
  - name: "AI-Enhanced Pattern"
    description: "Pattern for workflows using AI processing"
    activities:
      - "validate_inputs_activity"
      - "extract_context_activity"
      - "generate_recommendations_activity"
      - "semantic_search_activity"
      - "format_response_activity"
    
  - name: "Booking Pattern"
    description: "Pattern for booking and reservation workflows"
    activities:
      - "validate_inputs_activity"
      - "extract_context_activity"
      - "check_availability_activity"
      - "process_booking_request_activity"
      - "create_reservation_activity"
      - "format_response_activity"
