name: agent_workflow_generation
description: Agent-driven workflow generation with activity validation
version: 1.0.0
activities:
  - id: utility_service.validate_inputs_activity
    parameters:
      inputs: "${workflow.inputs}"
      schema: 
        workflow_name: "string"
        workflow_description: "string"
        requirements: "array"
  - id: workflow_composer_service.discover_available_activities_activity
    parameters: {}
  - id: workflow_composer_service.analyze_workflow_requirements_activity
    parameters:
      workflow_description: "${workflow.inputs.workflow_description}"
      requirements: "${workflow.inputs.requirements}"
  - id: workflow_composer_service.validate_activity_availability_activity
    parameters:
      required_activities: "${activities.analyze_workflow_requirements_activity.output.required_activities}"
      available_activities: "${activities.discover_available_activities_activity.output.available_activities}"
  - id: workflow_composer_service.generate_workflow_if_complete_activity
    parameters:
      workflow_name: "${workflow.inputs.workflow_name}"
      workflow_description: "${workflow.inputs.workflow_description}"
      validation_result: "${activities.validate_activity_availability_activity.output}"
  - id: utility_service.format_response_activity
    parameters:
      results: "${activities.generate_workflow_if_complete_activity.output}"
      format_type: "json"
