workflows:
- activities:
  - id: utility_service.validate_inputs_activity
    parameters:
      inputs: ${workflow.inputs}
      schema:
        feedback: string
  - id: ai_service.generate_recommendations_activity
    parameters:
      count: 3
      user_preferences: ${activities.0.validation_result.feedback}
  - id: utility_service.format_response_activity
    parameters:
      format_type: response
      results: ${activities.1.recommendations}
  description: A workflow that processes customer feedback, extracting sentiment,
    categorizing issues, and generating response recommendations.
  name: Customer Feedback Processing
  version: 1.0.0
