workflows:
- activities:
  - id: utility_service.validate_inputs_activity
    parameters:
    - input_name: data
      name: inputs
      source: input
    result_key: validated
  description: Workflow created via REST API
  name: RESTTestWorkflow
  version: 1.0.0
