workflows:
- activities:
  - id: utility_service.validate_inputs_activity
    parameters:
    - input_name: user_input
      name: inputs
      source: input
    result_key: validated_inputs
  - id: utility_service.format_response_activity
    parameters:
    - name: results
      result_name: validated_inputs
      source: activity_result
    - input_name: format
      name: format_type
      source: input
    result_key: formatted_output
  description: A simple workflow for testing
  name: SimpleTestWorkflow
  version: 1.0.0
