name: Deploy with Dagger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Dagger CLI
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | sh
          sudo mv bin/dagger /usr/local/bin
          dagger version

      - name: Run Dagger Pipeline in Docker
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
          GITHUB_ACTIONS: ${{ env.GITHUB_ACTIONS }}
        run: |
          docker run --rm \
            -v ${PWD}:/app \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /app \
            -e DOCKERHUB_USERNAME \
            -e DOCKERHUB_TOKEN \
            -e DAGGER_CLOUD_TOKEN \
            -e OPENAI_API_KEY \
            -e LLM_MODEL \
            -e GITHUB_ACTIONS \
            -e CI=true \
            python:3.11-slim \
            sh -c "apt-get update && apt-get install -y docker.io && pip install dagger-io python-dotenv && python ci/dagger_pipeline.py"
